const form = {
  messageName: "Message Name",
  declarationType: "Declaration Type",
  declarationType1: "Declaration Type(1:1)",
  declarationType2: "Declaration Type(1:2)",
  consignor: "Consigor/Exporter",
  name: "Name",
  address1: "Address1",
  address2: "Address2",
  postalCode: "Postal Code",
  city: "City",
  country: "Country",
  consignee: "Consignee",
  orgNumber: "Org. Number",
  customCreditNumber: "Custom Credit Number",
  defferredPayment: "Defferred Payment",
  declarant: "Declarant",
  contactPerson: "Contact Person",
  termsOfDelivery: "Terms of Delivery",
  deliveryPlace: "Delivery Place",
  countryOfDispatch: "Country of dispatch / Export",
  nationalityOfTransportAtBorder: "Nationality of transport of the border",
  modeOfTransportAtBorder: "Mode of transport at the border",
  locationOfGoods: "Location of Goods",
  supervisingCustomOffice: "Supervising Custom Office",
  deliveryAndTransport: "Delivery and Transport",
  valueDetails: "Value Details",
  freightOutwardNDK: "Freight, Outward NDK",
  totalInvoiceAmount: "Total Invoice Amount",
  amount: "Amount",
  currency: "Currency",
  rate: "Rate",
  references: "References",
  type: "Type",
  invoiceDate: "Invoice Date",
  reference: "Reference",
  add: "Add",
  header: "Header",
  import: "Import",
  declarationId: "Declaration ID",
  totalNumberOfPackages: "Total # of packages",
  totalNumberOfItems: "Total # of items",
  totalGrossMass: "Total Gross Mass",
  declarationStatus: "Declaration Status",
  customResponse: "Custom Response",
  taxationDate: "Taxation Date",
  logout: "Logout",
  declaration: "Declaration",
  home: "Home",
  case: "Case",
  caseManagement: "Case Management",
  createNewCase: "Create New Case",
  createNewDeclaration: "Create New Declaration",
  searchCases:"Search Cases",
  searchDeclarations:"Search Declarations",
  dashboard: "Dashboard",
  openCases: "Open Cases"
};
export default {
  form
};
