const form = {
  messageName: "Meddelande namn",
  declarationType: "Deklarationstyp",
  declarationType1: "Deklarationstyp(1:1)",
  declarationType2: "Deklarationstyp(1:2)",
  consignor: "Avsändaren / exportören",
  name: "Namn",
  address1: "Adress1",
  address2: "Adress2",
  postalCode: "Postnummer",
  city: "Stad",
  country: "Land",
  consignee: "Mottagare",
  orgNumber: "Org. siffra",
  customCreditNumber: "Anpassat kreditnummer",
  defferredPayment: "Uppskjuten betalning",
  declarant: "Deklaranten",
  contactPerson: "Kontaktperson",
  termsOfDelivery: "Leveransvillkor",
  deliveryPlace: "Leveransplats(20:2)",
  countryOfDispatch: "Land för avsändande / Export",
  nationalityOfTransportAtBorder: "Nationalitet för transport vid gränsen(21)",
  modeOfTransportAtBorder: "Transportläge vid gränsen(25)",
  locationOfGoods: "Plats för varor(30)",
  supervisingCustomOffice: "Övervakar tullkontoret",
  deliveryAndTransport: "Leverans och transport",
  valueDetails: "Värde detaljer",
  freightOutwardNDK: "Frakt, utåt NDK",
  totalInvoiceAmount: "Totalt Fakturabelopp",
  amount: "Belopp",
  currency: "Valuta",
  rate: "Betygsätta",
  references: "Referenser",
  type: "Typ",
  invoiceDate: "Fakturadatum",
  reference: "Referens",
  add: "Lägg till",
  header: "Rubrik",
  import: "Importera",
  declarationId: "Deklaration ID",
  totalNumberOfPackages: "Totalt # paket",
  totalNumberOfItems: "Totalt # föremål",
  totalGrossMass: "Total bruttomassa",
  declarationStatus: "Förklaringens status",
  customResponse: "Anpassat Svar",
  taxationDate: "Beskattningsdatum",
  logout: "Loggaut",
  declaration: "Deklaration",
  home: "Hem",
  case: "Fall",
  caseManagement: "Ärendehantering",
  createNewCase: "Skapa nytt fall",
  searchCases: "Sök fall",
  searchDeclarations: "Sök deklaration",
  createNewDeclaration: "Skapa en ny deklaration",
  dashboard: "Instrumentbräda",
  openCases: "Öppna fall"
};

export default {
  form
};
