export default{
    caseId:"Case Id",
    createdDate:"Created Date",
    priority:"Priority",
    status:"Status",
    client:"Client",
    clientIdentifier:"Client Identifier",
    identifierType:"Identifier Type",
    name:"Name",
    address:"Address",
    postalCode:"Postal Code",
    city:"City",
    country:"Country",
    email:"Email",
    caseInformation:"Case Information",
    description:"Description",
    messageFromClient:"Message From Client",
    references:"References",
    type:"Type",
    identity:"Identity",
    comment:"Comment",
    notes:"Notes",
    notesByCPA:"Notes By CPA",
    caseStatus:"Case Status"
}