export default [
    {
        type:"appCustomTextBox",
        title:"client",
        value:"",
        valueType:String,
        dataType:"StringMatch",
        props:{id:"client",label:"Client"},
        show:false
    },
    {
        type:"appCustomMultiSelectDropDown",
        title:"status",
        value:[],
        valueType:Array,
        dataType:"EnumRange",
        props:{id:"status",label:"Status",dataSource:"/statustypes"},
        show:false
    },
    {
        type:"appCustomMultiSelectDropDown",
        title:"priority",
        value:[],
        dataType:"EnumRange",
        valueType:Array,
        props:{id:"priority",label:"Priority",dataSource:"/prioritytypes"},
        show:false
    },
    {
        type:"appCustomDateRangePicker",
        title:"createdOn",
        value: [],
        valueType:Array,
        dataType:"DateRange",
        props:{id:"createdOn",label:"CreatedOn"},
        show:false
    },

]