export default{
    caseId:"Case Id",
    createdDate:"Skapat Datum",
    priority:"Prioritet",
    status:"Status",
    client:"Klient",
    clientIdentifier:"Klient Identifierare",
    identifierType:"Identifierare Typ",
    name:"Namn",
    address:"Adress",
    postalCode:"Postnummer",
    city:"Stad",
    country:"Land",
    email:"E-post",
    caseInformation:"Case Information",
    description:"Beskrivning",
    messageFromClient:"Meddelande Från Klienten",
    references:"Referenser",
    type:"Typ",
    identity:"Identitet",
    comment:"Kommentar",
    notes:"anteckningar",
    notesByCPA:"Anteckningar av CPA",
    caseStatus:"Case Status"
}