// <auto-generated />
namespace CTDS.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedreferencetable104 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedreferencetable104));
        
        string IMigrationMetadata.Id
        {
            get { return "201908080905309_addedreferencetable1.0.4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
